### PR TITLE
For best TitleBar visualization in Linux

### PR DESCRIPTION
**Pull request by JavGuerra**
Changes in titlebar menu and title color and size in TitleBar section.

### CODE REVIEW

**Comment by wormeyman** [comment]
Hey @JavGuerra can you post some screenshots with the differences? I've taken a look on windows but i'm having trouble seeing any changes, I don't have a linux box on me at the moment.

Also assuming we keep these changes you can remove the CSS comments before we merge.

**Comment by JavGuerra** [comment]
Of course.

In image 1, the over option menu is green, but when i select it (image 2), then the over option is blue now.

Also, I can not see the title file.

In image 3 the over option menu and the title file are correct.

theme

Regards.

**Comment by wormeyman** [comment]
Ok thanks, here is another idea. What if we just remove the whole title bar section and let adobe handle the styling of that part.

```css
/************** TitleBar *************/
/*
#titlebar,
.modal-bar {
    padding: 0 0 0 0;
    background-color: rgba(0, 0, 0, 0);
}
body.in-browser .modal-bar,
body:not(.has-appshell-menus) .modal-bar {
    border-top: 1px solid #e0f0fa;
    padding: 5px 10px;
    color: rgba(0, 0, 0, 0);
}
div.modal-bar div#find-group input#find-what,
div.modal-bar div#replace-group input#replace-with {
    border: none;
    box-shadow: none;
}
#titlebar ul.nav {
    float: none;
    margin-left: 0;
    background-color: rgba(0, 0, 0, 0);
}
#titlebar ul.nav:after {
    content: "";
    display: table;
    clear: both;
}
#titlebar ul.nav li.dropdown a.dropdown-toggle:hover {
    background: rgb(224, 240, 250) !important;
    border-color: #fff;
}
#titlebar div.title-wrapper {
    padding: 5px 0 5px 0;
}
#titlebar div.title-wrapper span.title {
    color: #808080;
    font-size: 18px;
    font-weight: normal;
}
#titlebar a.dropdown-toggle {
    font-weight: normal;
}
*/
/*************************************** Sidebars ***************************************/
```

**Comment by JavGuerra** [comment]
yes, that seems a better solution, and it work too. :)

**Comment by wormeyman** [comment]
https://github.com/Jacse/themes-for-brackets/tree/Stone-Age-Titlebar-Fixes

Take a look @Jacse @JavGuerra  I think this is the best option and we can merge this into master and push out an update.

**Comment by Jacse** [comment]
@wormeyman @JavGuerra I definitely think this is the way to go. Do other themes explicitly style the titlebar? I'm thinking we should remove said styling from all themes for the sake of consistency.

With that said I think we should merge so I can push out an update.

**Comment by Jacse** [comment]
Actually I just looked at #116 and with that in mind I guess the ultimate best thing to would be custom styling of the linux-titlebar for all themes.

I'll try to wrap my head around how that could be done in the weekend.

**Comment by JavGuerra** [comment]
@wormeyman @Jacse Well. Commenting the title bar does not disappear the file title, but the problem of the colors are corrected, as can you see in the image, at least in my version of Brackets.
captura

**Comment by wormeyman** [comment]
What resolution is your screen? that looks pretty low.

**Comment by JavGuerra** [comment]
@wormeyman The window is not maximized. :)

**Comment by Jacse** [comment]
@JavGuerra could you test the new version by removing the extension from Brackets and installing via the url -> https://github.com/Jacse/themes-for-brackets/

Alle titlebars should be dark now :+1: 

I know it isn't excactly what you asked for, but I think it's the best way to go.

**Comment by JavGuerra** [comment]
@Jacse  unfortunately, the result are not the expected... :cry: 

captura_2016-03-14

**Comment by Jacse** [comment]
You uninstalled the extension and installed directly from Github, right?

**Comment by JavGuerra** [comment]
@Jacse no. I only replace the css file. But now I try it, I remove the extension, download the github extension and install it in Bracket... this is the result...

reinstalando

**Comment by wormeyman** [comment]
Pulling from master works for me!

**Comment by Jacse** [comment]
@wormeyman I'll push out a new version to the Brackets plugin registry :+1:

**Pull request closed without merging**
